import "../styles/globals.css";

export const metadata = {
  title: "Gallerie Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {children}s
      </body>
    </html>
  );
}